In [2]:
import pandas as pd
import numpy as np
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.action_chains import ActionChains
from selenium.common.exceptions import NoSuchElementException, ElementNotInteractableException 
import time

In [40]:
# 2. CSV 파일 읽기
# lifestyle-entertainment, IoT, Support, BizIntel, AppFamilies, Website-AppBuilding, HumanResources, ArtificialIntelligence, Content-Files, Productivity, ITOperations, Communication, Commerce, Marketing, Sales-CRM
data = pd.read_excel("D:/code/kka_1/data/Zapier_AppFamilies_apps.xlsx")
print(data.shape)
data.head()

(127, 3)

,AppName,AppInfo,Url
0,Google Sheets,"Create, edit, and share spreadsheets wherever ...",https://zapier.com/apps/google-sheets/integrat...
1,Gmail,"One of the most popular email services, Gmail ...",https://zapier.com/apps/gmail/integrations
2,Filter by Zapier,Only allow a Zap to proceed when a certain con...,https://zapier.com/apps/filter/integrations
3,Formatter by Zapier,Data isn't always in the format you need. Perh...,https://zapier.com/apps/formatter/integrations
4,Webhooks by Zapier,Webhooks simply POST data (or JSON) to a speci...,https://zapier.com/apps/webhook/integrations

In [41]:
# 3. url 리스트 추출
url_list = data["Url"].tolist()
print(len(url_list), url_list[0])
app_list = data["AppName"].tolist()
print(len(app_list), app_list[0])

127 https://zapier.com/apps/google-sheets/integrations
127 Google Sheets

In [74]:
print(len(url_list))
print(url_list[0])

127
https://zapier.com/apps/google-sheets/integrations

In [80]:
urls = url_list
apps = app_list
driver = webdriver.Chrome()

for idx, url in enumerate(urls):
    print(f"\n[{idx+1}/{len(urls)}] 현재 URL: {url}")
    driver.get(url)
    driver.maximize_window()
    # WebDriverWait 객체 생성
    wait = WebDriverWait(driver, np.random.uniform(1,3))
    # container = wait.until(EC.presence_of_element_located((By.XPATH, '//*[@id="main"]/div/div[3]/div[4]/div/section/div[2]')))
#      container = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, 'div.css-ywpy44')))
    '//*[@id="main"]/div/div[3]/div[4]/div, //*[@id="main"]/div/div[3]/div[4]/div/section/div[2]'
    # 버튼이 더 이상 존재하지 않을 때까지 클릭
    while True:
        try:
            # 버튼이 존재하고 클릭 가능할 때까지 대기
    #         button = wait.until(EC.element_to_be_clickable((By.XPATH, button_xpath)))button class="_base-button_rr5dn_1
            # //*[@id="zap-template-list"]/div[2]/div/button
    #         button = wait.until(EC.element_to_be_clickable((By.XPATH, '//button[@class, "_base-button_rr5dn_1"')))
            button = wait.until(EC.element_to_be_clickable((By.XPATH, '//*[@id="main"]/div/div[3]/div[5]/div/section/div[3]/button')))
    #         button = wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, 'button._base-button_rr5dn_1')))
            # 버튼이 화면 내에 위치하도록 스크롤 조정
    #         driver.execute_script("arguments[0].scrollIntoView();", button)
            driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
            time.sleep(1)  # 스크롤 반영 대기
            # JavaScript를 사용하여 클릭
            driver.execute_script("arguments[0].click();", button)
            # 클릭 후 페이지가 반응할 시간을 부여
            time.sleep(np.random.uniform(2,3))            
        except Exception as e:
            # print("더 이상 클릭할 버튼 없음:", e)
            break  # 버튼이 없으면 루프 종료
    # 모든 앱 액션 div 찾기
    app_actions = driver.find_elements(By.XPATH, "//div[contains(@class, 'css-1ybx9px')]")
    print(len(app_actions))
    # 데이터 저장 리스트
    actioin_list = []
    for action in app_actions:
        try:
    #        category = action.find_element(By.CLASS_NAME, "_tootip-wrapper_8x43p_1").text
            category = action.find_element(By.CSS_SELECTOR, "div._tooltip-wrapper_8x43p_1 span").text  # TnA Category : <div class="_tooltip-wrapper_8x43p_1">
        except:
            category = None

        try:
    #         do = action.find_element(By.XPATH, "//span[contains(@class, 'css-1kefmdn')]").text
            do = action.find_element(By.CSS_SELECTOR, "span.css-1kefmdn").text # TnA Do  : <span class="css-1kefmdn">
        except:
            do = None

        try:
            name = action.find_element(By.CLASS_NAME, "app-action__title.css-pgz5n6").text # TnA Name : <span class="app-action__title css-pgz5n6">
    #          name = action.find_element(By.XPATH, "//span[contains(@class, 'app-action__title css-pgz5n6')]").text
        except:
            name = None

        try:
            description = action.find_element(By.CLASS_NAME, "css-1nnqqud").text # TnA Description : <p class="css-1nnqqud">
        except:
            description = None
        actioin_list.append([category, do, name, description])
    df = pd.DataFrame(actioin_list, columns=["Category", "Do", "Name", "Description"])
    df.to_csv("D:/code/kka_1/data/Apps_TnA/AppFamilies/{}_TrigActList.csv".format(apps[idx]), encoding='UTF-8', index=False)
    time.sleep(np.random.uniform(2,3))
    print(df.shape)

[1/127] 현재 URL: https://zapier.com/apps/google-sheets/integrations
25
(25, 4)

[2/127] 현재 URL: https://zapier.com/apps/gmail/integrations
17
(17, 4)

[3/127] 현재 URL: https://zapier.com/apps/filter/integrations
0
(0, 4)

[4/127] 현재 URL: https://zapier.com/apps/formatter/integrations
4
(4, 4)

[5/127] 현재 URL: https://zapier.com/apps/webhook/integrations
7
(7, 4)

[6/127] 현재 URL: https://zapier.com/apps/google-calendar/integrations
18
(18, 4)

[7/127] 현재 URL: https://zapier.com/apps/schedule/integrations
5
(5, 4)

[8/127] 현재 URL: https://zapier.com/apps/paths/integrations
1
(1, 4)

[9/127] 현재 URL: https://zapier.com/apps/email/integrations
3
(3, 4)

[10/127] 현재 URL: https://zapier.com/apps/google-drive/integrations
20
(20, 4)

[11/127] 현재 URL: https://zapier.com/apps/delay/integrations
3
(3, 4)

[12/127] 현재 URL: https://zapier.com/apps/code/integrations
4
(4, 4)

[13/127] 현재 URL: https://zapier.com/apps/google-forms/integrations
3
(3, 4)

[14/127] 현재 URL: https://zapier.com/apps/facebook-lead-ads/integrations
1
(1, 4)

[15/127] 현재 URL: https://zapier.com/apps/microsoft-outlook/integrations
25
(25, 4)

[16/127] 현재 URL: https://zapier.com/apps/rss/integrations
3
(3, 4)

[17/127] 현재 URL: https://zapier.com/apps/zapier-tables/integrations
19
(19, 4)

[18/127] 현재 URL: https://zapier.com/apps/gravity-forms/integrations
3
(3, 4)

[19/127] 현재 URL: https://zapier.com/apps/google-docs/integrations
9
(9, 4)

[20/127] 현재 URL: https://zapier.com/apps/looping/integrations
3
(3, 4)

[21/127] 현재 URL: https://zapier.com/apps/email-parser/integrations
2
(2, 4)

[22/127] 현재 URL: https://zapier.com/apps/youtube/integrations
8
(8, 4)

[23/127] 현재 URL: https://zapier.com/apps/google-contacts/integrations
10
(10, 4)

[24/127] 현재 URL: https://zapier.com/apps/excel/integrations
12
(12, 4)

[25/127] 현재 URL: https://zapier.com/apps/ai/integrations
1
(1, 4)

[26/127] 현재 URL: https://zapier.com/apps/facebook-pages/integrations
10
(10, 4)

[27/127] 현재 URL: https://zapier.com/apps/sms/integrations
1
(1, 4)

[28/127] 현재 URL: https://zapier.com/apps/google-ads/integrations
14
(14, 4)

[29/127] 현재 URL: https://zapier.com/apps/google-tasks/integrations
10
(10, 4)

[30/127] 현재 URL: https://zapier.com/apps/woocommerce/integrations
12
(12, 4)

[31/127] 현재 URL: https://zapier.com/apps/google-business-profile/integrations
4
(4, 4)

[32/127] 현재 URL: https://zapier.com/apps/zoho-crm/integrations
19
(19, 4)

[33/127] 현재 URL: https://zapier.com/apps/wordpress/integrations
14
(14, 4)

[34/127] 현재 URL: https://zapier.com/apps/zapier-manager/integrations
12
(12, 4)

[35/127] 현재 URL: https://zapier.com/apps/weather/integrations
4
(4, 4)

[36/127] 현재 URL: https://zapier.com/apps/microsoft-todo/integrations
10
(10, 4)

[37/127] 현재 URL: https://zapier.com/apps/facebook-conversions/integrations
0
(0, 4)

[38/127] 현재 URL: https://zapier.com/apps/microsoft-teams/integrations
16
(16, 4)

[39/127] 현재 URL: https://zapier.com/apps/storage/integrations
15
(15, 4)

[40/127] 현재 URL: https://zapier.com/apps/wpforms/integrations
2
(2, 4)

[41/127] 현재 URL: https://zapier.com/apps/linkedin-ads/integrations
8
(8, 4)

[42/127] 현재 URL: https://zapier.com/apps/interfaces/integrations
11
(11, 4)

[43/127] 현재 URL: https://zapier.com/apps/sub-zap-by-zapier/integrations
3
(3, 4)

[44/127] 현재 URL: https://zapier.com/apps/instagram-for-business/integrations
4
(4, 4)

[45/127] 현재 URL: https://zapier.com/apps/onedrive/integrations
11
(11, 4)

[46/127] 현재 URL: https://zapier.com/apps/linkedin/integrations
3
(3, 4)

[47/127] 현재 URL: https://zapier.com/apps/google-chat/integrations
1
(1, 4)

[48/127] 현재 URL: https://zapier.com/apps/url-shortener/integrations
1
(1, 4)

[49/127] 현재 URL: https://zapier.com/apps/office-365/integrations
18
(18, 4)

[50/127] 현재 URL: https://zapier.com/apps/facebook-messenger/integrations
2
(2, 4)

[51/127] 현재 URL: https://zapier.com/apps/google-slides/integrations
5
(5, 4)

[52/127] 현재 URL: https://zapier.com/apps/smtp/integrations
1
(1, 4)

[53/127] 현재 URL: https://zapier.com/apps/google-ai-studio/integrations
2
(2, 4)

[54/127] 현재 URL: https://zapier.com/apps/sharepoint/integrations
19
(19, 4)

[55/127] 현재 URL: https://zapier.com/apps/ninjaforms/integrations
1
(1, 4)

[56/127] 현재 URL: https://zapier.com/apps/zoho-forms/integrations
2
(2, 4)

[57/127] 현재 URL: https://zapier.com/apps/formidable/integrations
3
(3, 4)

[58/127] 현재 URL: https://zapier.com/apps/digest/integrations
3
(3, 4)

[59/127] 현재 URL: https://zapier.com/apps/facebook-custom-audiences/integrations
4
(4, 4)

[60/127] 현재 URL: https://zapier.com/apps/zapier-chrome-extension/integrations
2
(2, 4)

[61/127] 현재 URL: https://zapier.com/apps/web-parser-by-zapier/integrations
1
(1, 4)

[62/127] 현재 URL: https://zapier.com/apps/translate/integrations
2
(2, 4)

[63/127] 현재 URL: https://zapier.com/apps/zoho-mail/integrations
9
(9, 4)

[64/127] 현재 URL: https://zapier.com/apps/files-by-zapier/integrations
4
(4, 4)

[65/127] 현재 URL: https://zapier.com/apps/learndash/integrations
12
(12, 4)

[66/127] 현재 URL: https://zapier.com/apps/imap/integrations
2
(2, 4)

[67/127] 현재 URL: https://zapier.com/apps/onenote/integrations
7
(7, 4)

[68/127] 현재 URL: https://zapier.com/apps/microsoft-dynamics-crm/integrations
52
(52, 4)

[69/127] 현재 URL: https://zapier.com/apps/zoho-books/integrations
11

KeyboardInterrupt:

In [57]:
print(url_list[:5])

['https://zapier.com/apps/google-sheets/integrations', 'https://zapier.com/apps/gmail/integrations', 'https://zapier.com/apps/filter/integrations', 'https://zapier.com/apps/formatter/integrations', 'https://zapier.com/apps/webhook/integrations']

In [77]:
driver = webdriver.Chrome()
#driver.get('https://zapier.com/apps/google-sheets/integrations')
driver.get('https://zapier.com/apps/gmail/integrations')
driver.maximize_window()

In [78]:
# WebDriverWait 객체 생성
wait = WebDriverWait(driver, np.random.uniform(1,3))
# container = wait.until(EC.presence_of_element_located((By.XPATH, '//*[@id="main"]/div/div[3]/div[4]/div/section/div[2]')))
# container = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, 'div.css-ywpy44')))
'//*[@id="main"]/div/div[3]/div[4]/div, //*[@id="main"]/div/div[3]/div[4]/div/section/div[2]'
# 버튼이 더 이상 존재하지 않을 때까지 클릭
while True:
    try:
        # 버튼이 존재하고 클릭 가능할 때까지 대기
#         button = wait.until(EC.element_to_be_clickable((By.XPATH, button_xpath)))button class="_base-button_rr5dn_1
        # //*[@id="zap-template-list"]/div[2]/div/button
#         button = wait.until(EC.element_to_be_clickable((By.XPATH, '//button[@class, "_base-button_rr5dn_1"')))
        button = wait.until(EC.element_to_be_clickable((By.XPATH, '//*[@id="main"]/div/div[3]/div[5]/div/section/div[3]/button')))
#         button = wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, 'button._base-button_rr5dn_1')))
        # 버튼이 화면 내에 위치하도록 스크롤 조정
#         driver.execute_script("arguments[0].scrollIntoView();", button)
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        time.sleep(1)  # 스크롤 반영 대기
        # JavaScript를 사용하여 클릭
        driver.execute_script("arguments[0].click();", button)
        # 클릭 후 페이지가 반응할 시간을 부여
        time.sleep(np.random.uniform(2,3))            
    except Exception as e:
        # print("더 이상 클릭할 버튼 없음:", e)
        break  # 버튼이 없으면 루프 종료
# 모든 앱 액션 div 찾기
app_actions = driver.find_elements(By.XPATH, "//div[contains(@class, 'css-1ybx9px')]")
print(len(app_actions))

17

In [59]:
print(app_actions[0])
print(action.find_element(By.XPATH, "//span[contains(@class, 'css-1kefmdn')]").text)
# print(action.find_element(By.CSS_SELECTOR, "div._tootip-wrapper_8x43p_1 span").text)

<selenium.webdriver.remote.webelement.WebElement (session="cf37f24ea3c866e75e1aacf1407c8bb6", element="f.2BB6A4EE16A42879191C54ED164DAE0A.d.6BA991126410C4518815A24ECA0245F8.e.2801")>

InvalidSessionIdException: Message: invalid session id
Stacktrace:
	GetHandleVerifier [0x00007FF746EE4C25+3179557]
	(No symbol) [0x00007FF746B488A0]
	(No symbol) [0x00007FF7469D8FFC]
	(No symbol) [0x00007FF746A1F8DF]
	(No symbol) [0x00007FF746A57AF2]
	(No symbol) [0x00007FF746A5244E]
	(No symbol) [0x00007FF746A514F9]
	(No symbol) [0x00007FF7469A55E5]
	GetHandleVerifier [0x00007FF746F467CD+3579853]
	GetHandleVerifier [0x00007FF746F5D1D2+3672530]
	GetHandleVerifier [0x00007FF746F52153+3627347]
	GetHandleVerifier [0x00007FF746CB092A+868650]
	(No symbol) [0x00007FF746B52FFF]
	(No symbol) [0x00007FF7469A41FF]
	GetHandleVerifier [0x00007FF746FCFA28+4141608]
	BaseThreadInitThunk [0x00007FFC70137374+20]
	RtlUserThreadStart [0x00007FFC714FCC91+33]

In [79]:
actioin_list = []
for action in app_actions:
# TnA Category : <div class="_tooltip-wrapper_8x43p_1">
# TnA Do  : <span class="css-1kefmdn">
# TnA Name : <span class="app-action__title css-pgz5n6">
# TnA Description : <p class="css-1nnqqud">
    try:
#        category = action.find_element(By.CLASS_NAME, "_tootip-wrapper_8x43p_1").text
        category = action.find_element(By.CSS_SELECTOR, "div._tooltip-wrapper_8x43p_1 span").text
    except:
        category = None

    try:
#         do = action.find_element(By.XPATH, "//span[contains(@class, 'css-1kefmdn')]").text
        do = action.find_element(By.CSS_SELECTOR, "span.css-1kefmdn").text
    except:
        do = None

    try:
        name = action.find_element(By.CLASS_NAME, "app-action__title.css-pgz5n6").text
#          name = action.find_element(By.XPATH, "//span[contains(@class, 'app-action__title css-pgz5n6')]").text
    except:
        name = None

    try:
        description = action.find_element(By.CLASS_NAME, "css-1nnqqud").text
    except:
        description = None
    actioin_list.append([category, do, name, description])
df = pd.DataFrame(actioin_list, columns=["Category", "Do", "Name", "Description"])
df

,Category,Do,Name,Description
0,Trigger,Polling,New Attachment,Triggers when you receive a new attachment.
1,Trigger,Polling,New Labeled Email,Triggers when you label an email.
2,Trigger,Polling,New Email Matching Search,Triggers when you receive a new email that mat...
3,Trigger,Polling,New Thread,Triggers when a new thread starts.
4,Action,Write,Delete Email,Sends an email message to the trash.
5,Action,Write,Create Draft Reply,Create a draft reply to an existing email.
6,Action,Write,Send Email,Create and send a new email message.
7,Action,Write,Reply to Email,Send a reply to an email message.
8,Action,Search or write,Find or Send Email,Finds or creates a specific message.
9,Trigger,Polling,New Label,Triggers when you add a new label.
10,Trigger,Polling,New Email,Triggers when a new email appears in the speci...
11,Trigger,Polling,New Starred Email,Triggers when you receive a new email and star...
12,Action,Write,Add Label to Email,Add a label to an email message.
13,Action,Write,Create Draft,Create a draft email message.
14,Action,Write,Create Label,Creates a new label.
15,Action,Write,Remove Label From Email,Remove a label from an email message.
16,Action,Search,Find Email,Finds an email message.